Repository huggingface/neuralcoref, pull requests merged in 2019-10, with the labels that each got.

#213 Fix incorrect mention end index for using gold mentions
  neuralcoref/train/conllparser.py
Labels: bug, training

#211 Update training docs and code
  .gitignore
  neuralcoref/__init__.py
  neuralcoref/file_utils.py
  neuralcoref/train/algorithm.py
  neuralcoref/train/conll_processing_script/compile_coref_data.sh
  neuralcoref/train/conllparser.py
  neuralcoref/train/dataset.py
  neuralcoref/train/document.py
  neuralcoref/train/evaluator.py
  neuralcoref/train/learn.py
  neuralcoref/train/model.py
  neuralcoref/train/training.md
  neuralcoref/train/training_requirements.txt
  requirements.txt
Labels: bug, documentation, enhancement, training

#221 fixed typo : navigating the coreference cluster chains
  README.md
Labels: docs
